### PR TITLE
Strip configs (as they can now be autogenerated) and tidy up logging imports.

### PR DESCRIPTION
**Pull request by ehiggs**

### CODE REVIEW

**Comment by stdweird** [comment]
so only 2 config files are affected by the autoconfig stuff? that seems odd?

**Comment by ehiggs** [comment]
We smushed all the config into one file per distribution and we support Vanilla and 'ln -s' flavours of Hadoop 2.

**Comment by stdweird** [comment]
but configs like https://github.com/hpcugent/hanythingondemand/blob/master/etc/hod/Hadoop-2.5.0-cdh5.3.1-gpfs/hod.conf can't be reduced as well?

**Comment by ehiggs** [comment]
I reduced it a bit but it doesn't have its own generator so the config isn't completely gone.

**Pull request merged**
