### PR TITLE
Reduce time to check processes down to 15 from 60.

### PR DESCRIPTION
**Pull request by ehiggs**
Seems to make our startup faster my a linear amount.

Addresses #22.

### CODE REVIEW

**Comment by boegel** [comment]
@ehiggs: what's up with the failing tests?

Also, would it hurt to make this even tighter, e.g. 5s?

**Comment by boegel** [comment]
As discussed: can we use 5s during startup, and then switch back to 60s once the cluster is running?

**Comment by boegel** [comment]
@ehiggs: what's up with the tests? We need them green to merge this.

**Comment by ehiggs** [comment]
Jenkins, test this please.

**Comment by ehiggs** [comment]
I don't know what's up with the test. Jenkins claims it timed out fetching the branch after 10 minutes.

**Pull request merged**
