### PR TITLE
include label in localworkdir, if available

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by ehiggs** [comment]
I'm not sure what the benefit is here. If it's to help `hod clean` determine the localworkdir, that's better done by making another `hod.d/<label>/` file.

**Comment by boegel** [comment]
It's mostly so people can easily figure out which local workdir corresponds to which cluster, if they ever need to (e.g. when going to the HOD workdir, and navigating via `ls` and co).

It's not intended to make internal functionality easier.

**Comment by boegel** [comment]
Jenkins: test this please

**Pull request merged**
