### PR TITLE
Feature/h base

### LINKED ISSUE #81: support HBase?
cc @molden

### PR DESCRIPTION
**Pull request by molden**
fixes #81

### CODE REVIEW

**Comment by boegel** [comment]
@molden: great, thanks! I'll let @ehiggs take a look at this (and I'll tackle https://github.com/hpcugent/easybuild-easyconfigs/pull/1990)

**Comment by molden** [comment]
@ehiggs : as you may notice for HBase it is also necessary to launch the HDFS filesystem to work as HBase depends on it or at least it depends on a filesystem that implements the HDFS API. So in theory it should also work with a version of GPFS that implements the right APIs, if I'm not mistaken?

**Comment by molden** [comment]
@ehiggs : I could reproduce the error: 'port already in use' for the regionserver. So it is related to this bug in HBase: https://issues.apache.org/jira/browse/HBASE-13479. A workaround is submitted to the PR. I have tested this and it works.

**Comment by ehiggs** [comment]
Thanks for the fix to the patch. I've tested it by running the tutorial examples [here](http://akbarahmed.com/2012/08/13/hbase-command-line-tutorial/).

Thanks for the patch!

**Pull request merged**
