### PR TITLE
get rid of bin/hod-local, use python -m hod.subcommands.local instead

### PR DESCRIPTION
**Pull request by boegel**
fix for #35

### CODE REVIEW

**Comment by boegel** [comment]
@ehiggs: please rereview, I'm also moved `hod.subcommands.local` to `hod.local`

playing around with this now...

**Comment by boegel** [comment]
Seems to be working, I see an `ipython notebook` process running on the head node, and `hod.local` seems to be around on the other workernodes.

**Comment by ehiggs** [comment]
Awesome. I'll work with you on the tunnelling.

**Comment by boegel** [comment]
@ehiggs: then let's get this one merged? Tests pass, and it works as intended...

**Pull request merged**
