### PR TITLE
Send PBS_JOBID to the slaves so they can figure out the localworkdir.

### PR DESCRIPTION
**Pull request by ehiggs**
Intended to solve #121.

### CODE REVIEW

**Comment by stdweird** [comment]
why is this needed? (why isn't pbs_jobid set in the job env of the slaves? sounds like a pbs bug...)

**Comment by boegel** [comment]
@stdweird: doesn't `mympirun` also support specifying which environment variables should be passed down to the slaves, with a wildcard even, like `$PBS*`?

**Comment by stdweird** [comment]
@boegel yes, `mympirun --variablesprefix=PBS` should do that.

**Comment by ehiggs** [comment]
Indeed PBS_JOBID shows up in the slave. I have the following example script:

`env.sh`:
```bash
$ cat env.sh
#!/bin/bash

module load vsc-mympirun
module load OpenMPI
module load mpi4py
module load vsc-base
cd $PBS_O_WORKDIR
mympirun --hybrid 2 --output=${PBS_JOBID}.log $HOME/jobs/env.py
```

`env.py`:
```python
#!/usr/bin/env python

from mpi4py import MPI
import os
from vsc.utils import fancylogger

_log = fancylogger.getLogger(fname=False)

MASTERRANK = 0

if MPI.COMM_WORLD.rank == MASTERRANK:
    _log.warn('master: %s' % str(os.environ))
else:
    _log.warn('slave: %s' % str(os.environ))
```

And the `PBS_JOBID` is in the slave log. I'm going to close this and continue investigating.

**Pull request closed without merging**
